import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from './ui/card';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Badge } from './ui/badge';
import {
  FileText,
  Download,
  Filter,
  Calendar,
  Search,
  Eye,
  Trash2,
  TrendingUp,
  Users,
  Camera,
  AlertCircle
} from 'lucide-react';
import { toast } from 'sonner';
import { vigilClasses } from './vigil-theme';
import { ReportGenerationModal } from './ReportGenerationModal';

import { SHARED_REPORTS, Report } from '../data/reportsData';

export function AdminReports() {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedFilter, setSelectedFilter] = useState<'all' | 'violence' | 'crash' | 'custom'>('all');
  const [dateRange, setDateRange] = useState('last-30-days');
  const [reports, setReports] = useState<Report[]>(SHARED_REPORTS);

  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);

  const stats = [
    { label: 'Total Reports', value: reports.length.toString(), icon: FileText, color: 'text-blue-400' },
    { label: 'This Month', value: '18', icon: TrendingUp, color: 'text-green-400' },
    { label: 'Generated By Users', value: '24', icon: Users, color: 'text-purple-400' },
    { label: 'Total Incidents', value: reports.reduce((acc, r) => acc + (r.incidentsCount || 0), 0).toString(), icon: AlertCircle, color: 'text-red-400' },
  ];

  const filteredReports = reports.filter((report) => {
    const matchesSearch = report.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      report.id.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesFilter = selectedFilter === 'all' || report.type === selectedFilter;
    return matchesSearch && matchesFilter;
  });

  const handleGenerateReport = () => {
    setIsModalOpen(true);
  };

  const handleDeleteReport = (id: string) => {
    setReports(reports.filter(r => r.id !== id));
    toast.success("Report deleted permanently");
  };

  const handleDownload = (title: string) => {
    toast.success(`Downloading ${title}...`);
  };

  const handleView = (title: string) => {
    toast.info(`Opening ${title} preview...`);
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'violence':
        return 'bg-red-500/20 text-red-400 border-red-500/30';
      case 'crash':
        return 'bg-amber-500/20 text-amber-400 border-amber-500/30';
      case 'custom':
        return 'bg-blue-500/20 text-blue-400 border-blue-500/30';
      default:
        return 'bg-gray-500/20 text-gray-400 border-gray-500/30';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed':
        return 'bg-green-500/20 text-green-400 border-green-500/30';
      case 'processing':
        return 'bg-amber-500/20 text-amber-400 border-amber-500/30';
      case 'failed':
        return 'bg-red-500/20 text-red-400 border-red-500/30';
      default:
        return 'bg-gray-500/20 text-gray-400 border-gray-500/30';
    }
  };

  const handleReportGenerated = (newReport: Report) => {
    setReports([newReport, ...reports]);
  };

  return (
    <div className="space-y-6">
      {/* Report Generation Modal */}
      <ReportGenerationModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        role="admin"
        defaultTab="general"
        onGenerate={handleReportGenerated}
      />

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className={`text-2xl font-bold ${vigilClasses.textPrimary}`}>
            Admin Reports Management
          </h2>
          <p className={vigilClasses.textMuted}>
            View, generate, and manage all system reports with advanced filtering
          </p>
        </div>
        <Button
          className="bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-700 hover:to-blue-700 text-gray-900 dark:text-white"
          onClick={handleGenerateReport}
        >
          <FileText className="w-4 h-4 mr-2" />
          Generate New Report
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((stat) => {
          const Icon = stat.icon;
          return (
            <Card key={stat.label} className={vigilClasses.card}>
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className={`text-xs ${vigilClasses.textMuted} mb-1`}>{stat.label}</p>
                    <p className={`text-2xl font-bold ${stat.color}`}>{stat.value}</p>
                  </div>
                  <Icon className={`w-8 h-8 ${stat.color} opacity-50`} />
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Filters and Search */}
      <Card className={vigilClasses.card}>
        <CardContent className="p-4">
          <div className="flex flex-col md:flex-row gap-4">
            {/* Search */}
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <Input
                placeholder="Search reports by title or ID..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
            </div>

            {/* Type Filter */}
            <div className="flex gap-2">
              {['all', 'violence', 'crash', 'custom'].map((filter) => (
                <Button
                  key={filter}
                  variant={selectedFilter === filter ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setSelectedFilter(filter as typeof selectedFilter)}
                  className="capitalize"
                >
                  {filter === 'all' ? 'All Types' : filter}
                </Button>
              ))}
            </div>

            {/* Date Range */}
            <select
              value={dateRange}
              onChange={(e) => setDateRange(e.target.value)}
              className={`px-3 py-2 rounded-lg border ${vigilClasses.border} ${vigilClasses.bgCard} ${vigilClasses.textPrimary} text-sm`}
            >
              <option value="last-7-days">Last 7 Days</option>
              <option value="last-30-days">Last 30 Days</option>
              <option value="last-90-days">Last 90 Days</option>
              <option value="all-time">All Time</option>
            </select>
          </div>
        </CardContent>
      </Card>

      {/* Reports List */}
      <div className="space-y-3">
        {filteredReports.map((report) => (
          <Card key={report.id} className={`${vigilClasses.card} hover:border-cyan-500/30 transition-all`}>
            <CardContent className="p-4">
              <div className="flex items-start justify-between gap-4">
                {/* Report Info */}
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <FileText className="w-5 h-5 text-cyan-400" />
                    <h3 className={`font-semibold ${vigilClasses.textPrimary}`}>
                      {report.title}
                    </h3>
                    <Badge className={getTypeColor(report.type)}>
                      {report.type}
                    </Badge>
                    <Badge className={getStatusColor(report.status)}>
                      {report.status}
                    </Badge>
                  </div>

                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3">
                    <div>
                      <p className={`text-xs ${vigilClasses.textMuted}`}>Report ID</p>
                      <p className={`text-sm font-mono ${vigilClasses.textSecondary}`}>{report.id}</p>
                    </div>
                    <div>
                      <p className={`text-xs ${vigilClasses.textMuted}`}>Generated By</p>
                      <p className={`text-sm ${vigilClasses.textSecondary}`}>{report.generatedBy}</p>
                    </div>
                    <div>
                      <p className={`text-xs ${vigilClasses.textMuted}`}>Date</p>
                      <p className={`text-sm ${vigilClasses.textSecondary}`}>{report.generatedDate}</p>
                    </div>
                    <div>
                      <p className={`text-xs ${vigilClasses.textMuted}`}>File Size</p>
                      <p className={`text-sm ${vigilClasses.textSecondary}`}>{report.size}</p>
                    </div>
                  </div>

                  <div className="flex items-center gap-4 mt-3">
                    <div className="flex items-center gap-1.5">
                      <AlertCircle className="w-4 h-4 text-red-400" />
                      <span className={`text-xs ${vigilClasses.textMuted}`}>
                        {report.incidentsCount || 0} incidents
                      </span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <Camera className="w-4 h-4 text-cyan-400" />
                      <span className={`text-xs ${vigilClasses.textMuted}`}>
                        {report.camerasCount || 0} cameras
                      </span>
                    </div>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex flex-col gap-2">
                  <Button
                    size="sm"
                    variant="outline"
                    className="border-cyan-500/50 text-cyan-400 hover:bg-cyan-500/10"
                    onClick={() => handleView(report.title)}
                  >
                    <Eye className="w-4 h-4 mr-1" />
                    View
                  </Button>
                  <Button
                    size="sm"
                    className="bg-green-600 hover:bg-green-700 text-gray-900 dark:text-white"
                    disabled={report.status === 'processing'}
                    onClick={() => handleDownload(report.title)}
                  >
                    <Download className="w-4 h-4 mr-1" />
                    Download
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    className="border-red-500/50 text-red-400 hover:bg-red-500/10"
                    onClick={() => handleDeleteReport(report.id)}
                  >
                    <Trash2 className="w-4 h-4 mr-1" />
                    Delete
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {filteredReports.length === 0 && (
        <Card className={vigilClasses.card}>
          <CardContent className="p-12 text-center">
            <FileText className="w-16 h-16 mx-auto text-gray-400 mb-4" />
            <p className={`text-lg ${vigilClasses.textSecondary}`}>No reports found</p>
            <p className={vigilClasses.textMuted}>
              Try adjusting your search or filter criteria
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
